config/routes.rb
Rails.application.routes.draw do
  root :to => 'pages#index'

  resources :users, :only => [:new, :create, :index]
  resources :videos
  resources :centers
  resources :scubas
  resources :accounts, :only => [:index]
  get '/account/myvideos' => 'accounts#myvideos'
  get '/account/mycenters' => 'accounts#mycenters'
  get '/account/myscubas' => 'accounts#myscubas'
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/center.rb
class Center < ActiveRecord::Base
  belongs_to :user, :optional => true
  has_many :videos
end

app/models/scuba.rb
class Scuba < ActiveRecord::Base
  belongs_to :user, :optional => true
  has_many :videos
  belongs_to :center, :optional => true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, :presence => true, :uniqueness => true
  has_many :scubas
  has_many :videos
  has_many :centers
end

app/models/video.rb
class Video < ActiveRecord::Base
  belongs_to :user, :optional => true
  belongs_to :dive, :optional => true
  belongs_to :center, :optional => true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  # This controller exists to permit access to personal data and media instead of the full list of videos or diving center


  before_action :check_for_login

  def index
    @scubas = @current_user.scubas.all
  end

# This path to user videos is here to edit and see user's videos insted of searching in the full list with other users videos
  def myvideos
    @videos = @current_user.videos.all
  end

  def mycenters
    @centers = @current_user.centers.all
  end
# I create an alternate path to get access to the dive logs to edit or delete them. so you avoid mistake when you're just browsing your dives in the 'My dives' menu
  def myscubas
    @scubas = @current_user.scubas.all
  end


  private
    def user_params
      params.require(:user).permit(:name, :email, :pro, :password, :password_confirmation)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :fetch_user

  private
  def fetch_user
    @current_user = User.find_by :id => session[:user_id] if session[:user_id].present?
    session[:user_id] = nil unless @current_user.present?
  end

  def check_for_login
    redirect_to login_path unless @current_user.present?
  end
end

app/controllers/centers_controller.rb
class CentersController < ApplicationController
  def index
    @centers = Center.all.order(:country)
  end

  def new
    @center = Center.new
  end

  def create
    center = @current_user.centers.create center_params
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      center.photo = req["public_id"]
      center.save
    end
    redirect_to accounts_path
  end

  def edit
    @center = @current_user.centers.find params[:id]
  end

  def destroy
    center = @current_user.centers.find params[:id]
    center.destroy
    redirect_to accounts_path
  end

  def update
    center = @current_user.centers.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      center.photo = req["public_id"]
      center.update center_params
    end
    redirect_to accounts_path
  end

  def show
    @center = Center.find params[:id]
  end
  private
  def center_params
    params.require(:center).permit(:name, :country, :city, :photo, :website )
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @center = Center.all
    
  end
end

app/controllers/scubas_controller.rb
class ScubasController < ApplicationController

  before_action :check_for_login

  def index
    @scubas = @current_user.scubas.all
    @scubas_sort_by_date = @scubas.order(:date).reverse
  end

  def new
    @scuba = Scuba.new
  end

  def create
    @current_user.scubas.create scuba_params
    redirect_to accounts_path
  end

  def edit
    @scuba = @current_user.scubas.find params[:id]
  end

  def destroy
    scuba = @current_user.scubas.find params[:id]
    scuba.destroy
    redirect_to accounts_path
  end

  def update
    scuba = @current_user.scubas.find params[:id]
    scuba.update scuba_params
    redirect_to accounts_path
  end

  def show
    @scuba = @current_user.scubas.find params[:id]

  end

  private
  def scuba_params
    params.require(:scuba).permit(:title, :date, :location, :duration, :depth, :gps, :buddy, :notes )
  end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create

    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "invalid username or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    # NYI access for Admin
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
      if @user.save
        redirect_to root_path
      else
        render :new
      end
  end

  def edit
    # NYI access for Admin
  end

  def show
    @current_user.users.find params[:id]
  end


  private
    def user_params
      params.require(:user).permit(:name, :email, :pro, :password, :password_confirmation)
    end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController

  def index
    @videos = Video.all
  end

  # before_action :check_for_login

  def new
    @video = Video.new
  end

  def create
    @current_user.videos.create video_params
    redirect_to accounts_path
  end

  def edit
    @video = @current_user.videos.find params[:id]
  end

  def destroy
    video = @current_user.videos.find params[:id]
    video.destroy
    redirect_to accounts_path
  end

  def update
    video = @current_user.videos.find params[:id]
    video.update video_params
    redirect_to accounts_path
  end

  def show
    @video = Video.find params[:id]
    # this line is here to transform a regular URL to an embedded URL
    @video_url = @video.link.sub 'watch?v=', 'embed/'
  end

  private
  def video_params
    params.require(:video).permit(:name, :link)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/centers_helper.rb
module CentersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/scubas_helper.rb
module ScubasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/accounts/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>
<!-- not yet implemented for admin access editing fnctionalities -->

app/views/accounts/index.html.erb
<h1 class='title'>My account</h1>
<div class="account">

  <h3>My name: <%= @current_user.name %></h3>
  <h3>My email: <%= @current_user.email %></h3>

  <% if @current_user.pro? %>
    <p>This is a professional account</p>
    <p>Center: <span><%= @current_user.centers.count %></span> <%= link_to 'Manage my diving center', account_mycenters_path, :class => 'editlink' %></p>
  <% else %>
    <p>This is a personal account</p>
  <% end %>

  <p>Dive recorded: <span><%= @current_user.scubas.count %></span> <%= link_to 'Manage my dives', account_myscubas_path, :class => 'editlink' %></p>
  <p>Videos: <span><%= @current_user.videos.count %></span> <%= link_to 'Manage my videos', account_myvideos_path, :class => 'editlink' %></p>


  <%# this function check if the user have dives logged in his account %>
  <% @total = 0  %>
  <% if @scubas.size != 0 %>
    <% @scubas.each do |scuba| %>
      <% @total += scuba.duration %>
    <% end %>
    <p>Total time underwater: <span><%= @total / 60 %> hours and <%= @total % 60 %> minutes</span></p>
    <% @average = 0 %>
    <% @scubas.each do |scuba| %>
      <% @average += scuba.depth  %>
    <% end %>
    <p>Average depth: <span><%= @average / @scubas.size %> meters</span></p>
  <% end %>

</div>

app/views/accounts/mycenters.html.erb
<h1 class='title'>List of my centers</h1>

<% @centers.each do |center| %>
  <div class="centerlist">
    <h1><%= link_to center.name, center %></h1>
    <span><%= link_to 'edit informations', edit_center_path(center.id), :class => 'editlink' %></span>
  </div>
<% end %>

app/views/accounts/myscubas.html.erb
<h1 class='title'>List of my dives / edition</h1>

<% @scubas.each do |scuba| %>
  <div class="divelist">
    <h1><%= link_to scuba.title, scuba %></h1>
    <span><%= link_to 'edit informations', edit_scuba_path(scuba.id), :class => 'editlink' %></span>
  </div>
<% end %>

app/views/accounts/myvideos.html.erb
<h1 class='title'>List of my videos</h1>

<% @videos.each do |video| %>
  <div class="videolist">
    <h1><%= link_to video.name, video %></h1>
    <span><%= link_to 'edit name or url', edit_video_path(video.id), :class => 'editlink' %></span>
  </div>
<% end %>

app/views/centers/_form.html.erb
<%= form_for(@center, :class => 'form', :html => {:multipart => true}) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, :required => true, :autofocus => true, :placeholder => 'My diving Center' %>
  <%= f.label :country %>
  <%= f.text_field :country, :required => true, :placeholder => 'Australia' %>
  <%= f.label :city %>
  <%= f.text_field :city, :required => true, :placeholder => 'Sydney' %>
  <%= f.label :gps %>
  <%= f.text_field :gps, :required => true, :placeholder => '12.345, 34.567' %>
  <%= f.label :website %>
  <%= f.text_field :website, :required => true, :placeholder => 'http://www...' %>
  <%= f.label :photo %>
  <%= f.cl_image_upload :photo %>
  <%= f.submit 'Submit', :class => 'button' %>
<% end %>

app/views/centers/edit.html.erb
<h1 class='title'>Edit diving center informations</h1>
<div class="subtitle">
  <%= link_to "Delete this center", @center, :method => 'delete', :data => { :confirm => 'Are you sure?' }, :class => 'delete'%>
</div>

<%= render :partial => 'form' %>

app/views/centers/index.html.erb
<h1 class='title'>Diving centers</h1>
<p class='subtitle'>Click on a marker to get details</p>
<div id="worldmap"></div>
<p class='title'>Here the list of the diving centers:</p>
<div class="centerlist">
  <% @centers.each do |center| %>
    <div class="centerpart">
      <h2><%= link_to center.name, center %></h2>
      <p><%= center.country %></p>
    </div>
  <% end %>
</div>
<script>
  $(document).ready(function() {
    let worldMap = L.map('worldmap').setView([15, 36], 2);
    L.tileLayer('https://api.maptiler.com/maps/outdoor/{z}/{x}/{y}.png?key=7RCtJcLXrvnPQmX2OfA1', {
    attribution: '<a href="https://www.maptiler.com/copyright/" target="_blank">&copy; MapTiler</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>',
    }).addTo(worldMap);
    <%# this function loop the centers' coordinates to put a marker on the map and a link to the center page %>
    <% @centers.each do |center| %>
      L.marker([<%= center.gps %>]).addTo(worldMap).bindPopup(`<%= link_to center.name, center %>`);
    <% end %>
});
</script>

app/views/centers/new.html.erb
<h1 class='title'>Add your diving center</h1>

<%= render :partial => 'form' %>

app/views/centers/show.html.erb
<h1 class='title'><%= @center.name %></h1>

<div class="centerdetails">
  <div class="centerimg"><%= cl_image_tag(@center.photo, :class => 'centerimg') %></div>
  <div>Country: <%= @center.country %></div>
  <div>City: <%= @center.city %></div>
  <div>Contact name: <%= @center.user.name %></div>
  <div>Contact email: <%= @center.user.email %></div>

  <div>Website: <%= link_to @center.website, @center.website, target: :_blank %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Divr</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
    <div class="container">

      <nav>
        <p>divR</p>
        <ul>
          <li><%= link_to 'Home', root_path %></li>
          <li><%= link_to 'Videos', videos_path %></li>
          <li><%= link_to 'Diving Center', centers_path %></li>
          <li><%= link_to 'My Account', accounts_path %>
            <ul>
              <% if @current_user.present? %>
                <% if @current_user.pro? %>
                  <li><%= link_to 'Add a Center', new_center_path %></li>
                <% end %>
                <li><%= link_to 'Add Video', new_video_path %></li>
                <li><%= link_to 'Add Dive', new_scuba_path %></li>
                <li><%= link_to 'My Dives', scubas_path %></li>
                <li><%= link_to "Logout #{ @current_user.name }", login_path, :method => 'delete' %></li>
              <% else %>
                <li><%= link_to 'Sign up', new_user_path %></li>
                <li><%= link_to 'Login', login_path %></li>
              <% end %>
            </ul>
          </li>
        </ul>
      </nav>

      <div id="content">
        <%= yield %>
      </div>
      <div class="foot"></div>
      <footer>
        <a href="http://www.padi.com"><%= image_tag "padi.png" %></a>
      </footer>
      </div>
    </body>
  </html>

app/views/pages/index.html.erb
<div id="indexpages">
<h1>Welcome to divR</h1>
<p>divR is a new service for divers. You can log all your dives and track them on a map. You can share your videos with other users. And you'll find informations about our affiliate diving center.</p>
</div>

app/views/scubas/_form.html.erb
<%= form_for @scuba do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title, :required => true, :autofocus => true, :placeholder => '1st dive in...' %>
  <%= f.label :date %>
  <%= f.date_field :date, :required => true %>
  <%= f.label :location %>
  <%= f.text_field :location, :required => true, :placeholder => 'Sydney' %>
  <%= f.label :duration %>
  <%= f.number_field :duration, :required => true, :placeholder => 'in minutes' %>
  <%= f.label :depth %>
  <%= f.number_field :depth, :required => true, :placeholder => 'in meters' %>
  <%= f.label :gps %>
  <%= f.text_field :gps, :placeholder => '12.3456, 23.4567' %>
  <%= f.label :buddy %>
  <%= f.text_field :buddy, :placeholder => 'My diving buddy' %>
  <%= f.label :notes %>
  <%= f.text_area :notes, :placeholder => 'notes' %>
  <%= f.submit 'Submit', :class => 'button' %>
<% end %>

app/views/scubas/edit.html.erb
<h1 class='title'>Edit your dive</h1>
<div class="subtitle">
  <%= link_to "Delete this dive", @scuba, :method => 'delete', :data => { :confirm => 'Are you sure?' }, :class => 'delete'%>
</div>

<%= render :partial => 'form' %>

app/views/scubas/index.html.erb
<h1 class='title'>My dives</h1>


<% @scubas_sort_by_date.each do |scuba| %>
  <div class="divelist">
    <h3 ><%= link_to scuba.title, scuba %></h3>
    <span><p><%= scuba.date.strftime('%e %B %Y') %></p></span>
  </div>
<% end %>
<div id="worldmap"></div>

<script>
  $(document).ready(function() {
    let worldMap = L.map('worldmap').setView([15, 36], 2);
    L.tileLayer('https://api.maptiler.com/maps/outdoor/{z}/{x}/{y}.png?key=7RCtJcLXrvnPQmX2OfA1', {
    attribution: '<a href="https://www.maptiler.com/copyright/" target="_blank">&copy; MapTiler</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>',
    }).addTo(worldMap);
    var diveIcon = L.icon({
      iconUrl: '<%= image_path("diver.png") %>',

      iconSize:     [40, 40],
      iconAnchor:   [20, 20],
    });
    <% @scubas.each do |scuba| %>
      L.marker([<%= scuba.gps %>], {icon: diveIcon}).addTo(worldMap).bindPopup(`<%= link_to scuba.title, scuba %>`);

    <% end %>
});
</script>

app/views/scubas/new.html.erb
<h1 class='title'>Add a dive</h1>
<%= render :partial => 'form' %>

app/views/scubas/show.html.erb
<h1 class='title'>Dive details</h1>

<div class="divedetails">
  <h1><%= @scuba.title %></h1>
  <p><span class="key">Date:</span> <%= @scuba.date.strftime('%e %B %Y') %></p>
  <p><span class="key">Location:</span> <%= @scuba.location %></p>
  <p><span class="key">Duration:</span> <%= @scuba.duration %> minutes</p>
  <p><span class="key">Maximum Depth:</span> <%= @scuba.depth %> meters</p>
  <p><span class="key">Buddy:</span> <%= @scuba.buddy %></p>
  <p><span class="key">Notes:</span> <%= @scuba.notes %></p>
</div>

<div id="divemap"></div>

<%= link_to 'edit datas', edit_scuba_path %>
<script>
  $(document).ready(function() {
    let diveMap = L.map('divemap').setView([<%= @scuba.gps %>], 13);
    L.tileLayer('https://api.maptiler.com/maps/topographique/{z}/{x}/{y}.png?key=7RCtJcLXrvnPQmX2OfA1', {
    attribution: '<a href="https://www.maptiler.com/copyright/" target="_blank">&copy; MapTiler</a> <a href="https://www.openstreetmap.org/copyright" target="_blank">&copy; OpenStreetMap contributors</a>',
    }).addTo(diveMap);

    var diveIcon = L.icon({
      iconUrl: '<%= image_path("diver.png") %>',

      iconSize:     [40, 40],
      iconAnchor:   [20, 20],
    });
    L.marker([<%= @scuba.gps %>], {icon: diveIcon}).addTo(diveMap);


    var circle = L.circle([<%= @scuba.gps %>], {
    color: '#2E0560',
    fillColor: '#2E0560',
    fillOpacity: 0.3,
    radius: 200
  }).addTo(diveMap);
});
</script>

app/views/session/new.html.erb
<h1>Sign in</h1>

<% if flash[:error].present? %>
  <h2><%= flash[:error] %></h2>
<% end %>

<%= form_tag login_path do  %>
  <%= label_tag :email %>
  <%= email_field_tag :email %>

  <%= label_tag :password %>
  <%= password_field_tag :password %>

  <%= submit_tag "Sign in", :class => 'button' %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, :required => true, :autofocus => true, :placeholder => 'My name' %>
  <%= f.label :email %>
  <%= f.text_field :email, :required => true, :placeholder => 'name@mail.com' %>
  <%= f.label :pro %>
  <%= f.check_box :pro %>
  <%= f.label :password %>
  <%= f.password_field :password, :required => true, :placeholder => '8 characters minimum' %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, :placeholder => 'retype your password' %>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>My account</h1>
<h1>My name: <%= @current_user.name %></h1>
<h1>Mon eMail: <%= @current_user.email %></h1>

app/views/users/new.html.erb
<h1>Create an account</h1>

<%= render :partial => 'form' %>

app/views/users/show.html.erb
<h1>My account</h1>
<h1><%= @user.name %></h1>

app/views/videos/_form.html.erb
<%= form_for @video do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name, :required => true, :autofocus => true, :placeholder => '1st dive ...' %>

  <%= f.label :link %>
  <%= f.text_field :link, :required => true, :placeholder => 'http://...' %>

  <%= f.submit 'Submit', :class => 'button' %>
<% end %>

app/views/videos/edit.html.erb
<h1 class='title'>Edit title and URL of your video</h1>
<div class="subtitle">
  <%= link_to "Delete this video", @video, :method => 'delete', :data => { :confirm => 'Are you sure?' }, :class => 'delete'%>
</div>

<%= render :partial => 'form' %>

app/views/videos/index.html.erb
<h1 class='title'>List of videos</h1>

<% @videos.each do |video| %>
<div class="videolist">
  <%# This line create a thumbnail from the regular yoube URL %>
  <%= link_to image_tag((video.link.sub('https://www.youtube.com/watch?v=', 'http://img.youtube.com/vi/') + '/mqdefault.jpg'), :class => 'thumb'), video %>
  <h3><%= link_to video.name, video %></h3>
  <p>by: <%= video.user.name %></p>
</div>
<% end %>

app/views/videos/new.html.erb
<h1 class='title'>Add a video</h1>

<%= render :partial => 'form' %>

app/views/videos/show.html.erb
<h1 class='title'><%= @video.name %></h1>
<div class="videolist">
<iframe width="560" height="315" src='<%= @video_url %>' frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
<p>By: <%= @video.user.name %></p>
</div>